
CREATE TYPE __pivot_enum_0_0 AS ENUM ( '(no genres listed)', 'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western' );


CREATE TABLE date_dim(date_key DATE, day_of_year BIGINT, week_key BIGINT, week_of_year BIGINT, day_of_week BIGINT, iso_day_of_week BIGINT, day_name VARCHAR, first_day_of_week DATE, last_day_of_week DATE, month_key VARCHAR, month_of_year BIGINT, day_of_month BIGINT, month_name_short VARCHAR, month_name VARCHAR, first_day_of_month DATE, last_day_of_month DATE, quarter_key INTEGER, quarter_of_year BIGINT, day_of_quarter INTEGER, quarter_desc_short VARCHAR, quarter_desc VARCHAR, first_day_of_quarter DATE, last_day_of_quarter DATE, year_key INTEGER, first_day_of_year DATE, last_day_of_year TIMESTAMP, ordinal_weekday_of_month BIGINT);
CREATE TABLE driver(userId BIGINT, number_reviews BIGINT, average_rating DOUBLE);
CREATE TABLE driver2(userId BIGINT, number_reviews BIGINT, average_rating DOUBLE, "(no genres listed)_avg_rating_genre_feature" DOUBLE, "(no genres listed)_num_rating_genre_feature" BIGINT, Action_avg_rating_genre_feature DOUBLE, Action_num_rating_genre_feature BIGINT, Adventure_avg_rating_genre_feature DOUBLE, Adventure_num_rating_genre_feature BIGINT, Animation_avg_rating_genre_feature DOUBLE, Animation_num_rating_genre_feature BIGINT, Children_avg_rating_genre_feature DOUBLE, Children_num_rating_genre_feature BIGINT, Comedy_avg_rating_genre_feature DOUBLE, Comedy_num_rating_genre_feature BIGINT, Crime_avg_rating_genre_feature DOUBLE, Crime_num_rating_genre_feature BIGINT, Documentary_avg_rating_genre_feature DOUBLE, Documentary_num_rating_genre_feature BIGINT, Drama_avg_rating_genre_feature DOUBLE, Drama_num_rating_genre_feature BIGINT, Fantasy_avg_rating_genre_feature DOUBLE, Fantasy_num_rating_genre_feature BIGINT, "Film-Noir_avg_rating_genre_feature" DOUBLE, "Film-Noir_num_rating_genre_feature" BIGINT, Horror_avg_rating_genre_feature DOUBLE, Horror_num_rating_genre_feature BIGINT, IMAX_avg_rating_genre_feature DOUBLE, IMAX_num_rating_genre_feature BIGINT, Musical_avg_rating_genre_feature DOUBLE, Musical_num_rating_genre_feature BIGINT, Mystery_avg_rating_genre_feature DOUBLE, Mystery_num_rating_genre_feature BIGINT, Romance_avg_rating_genre_feature DOUBLE, Romance_num_rating_genre_feature BIGINT, "Sci-Fi_avg_rating_genre_feature" DOUBLE, "Sci-Fi_num_rating_genre_feature" BIGINT, Thriller_avg_rating_genre_feature DOUBLE, Thriller_num_rating_genre_feature BIGINT, War_avg_rating_genre_feature DOUBLE, War_num_rating_genre_feature BIGINT, Western_avg_rating_genre_feature DOUBLE, Western_num_rating_genre_feature BIGINT);
CREATE TABLE genre_dim(movieId BIGINT, genre VARCHAR);
CREATE TABLE movie_dim(movieId BIGINT, title VARCHAR, extracted_title VARCHAR, year_released VARCHAR, imdbId VARCHAR, tmdbId BIGINT);
CREATE TABLE ratings_fact(userId BIGINT, movieId BIGINT, rating DOUBLE, "timestamp" BIGINT, rating_date DATE);
CREATE TABLE user_dim(userId BIGINT, date_joined DATE);
CREATE TABLE user_matrix(userId BIGINT, number_reviews BIGINT, average_rating DOUBLE, Action_avg_rating_genre_feature DOUBLE, Action_num_rating_genre_feature BIGINT, Adventure_avg_rating_genre_feature DOUBLE, Adventure_num_rating_genre_feature BIGINT, Animation_avg_rating_genre_feature DOUBLE, Animation_num_rating_genre_feature BIGINT, Children_avg_rating_genre_feature DOUBLE, Children_num_rating_genre_feature BIGINT, Comedy_avg_rating_genre_feature DOUBLE, Comedy_num_rating_genre_feature BIGINT, Crime_avg_rating_genre_feature DOUBLE, Crime_num_rating_genre_feature BIGINT, Documentary_avg_rating_genre_feature DOUBLE, Documentary_num_rating_genre_feature BIGINT, Drama_avg_rating_genre_feature DOUBLE, Drama_num_rating_genre_feature BIGINT, Fantasy_avg_rating_genre_feature DOUBLE, Fantasy_num_rating_genre_feature BIGINT, "Film-Noir_avg_rating_genre_feature" DOUBLE, "Film-Noir_num_rating_genre_feature" BIGINT, Horror_avg_rating_genre_feature DOUBLE, Horror_num_rating_genre_feature BIGINT, IMAX_avg_rating_genre_feature DOUBLE, IMAX_num_rating_genre_feature BIGINT, Musical_avg_rating_genre_feature DOUBLE, Musical_num_rating_genre_feature BIGINT, Mystery_avg_rating_genre_feature DOUBLE, Mystery_num_rating_genre_feature BIGINT, Romance_avg_rating_genre_feature DOUBLE, Romance_num_rating_genre_feature BIGINT, "Sci-Fi_avg_rating_genre_feature" DOUBLE, "Sci-Fi_num_rating_genre_feature" BIGINT, Thriller_avg_rating_genre_feature DOUBLE, Thriller_num_rating_genre_feature BIGINT, War_avg_rating_genre_feature DOUBLE, War_num_rating_genre_feature BIGINT, Western_avg_rating_genre_feature DOUBLE, Western_num_rating_genre_feature BIGINT);

CREATE TEMPORARY VIEW links AS SELECT * FROM "/Users/yashwanth/Documents/GWU/Sem 3/Data Mining/Class 2/Class Material/ml-latest-small/links.csv";
CREATE TEMPORARY VIEW movies AS SELECT * FROM "/Users/yashwanth/Documents/GWU/Sem 3/Data Mining/Class 2/Class Material/ml-latest-small/movies.csv";
CREATE TEMPORARY VIEW ratings AS SELECT * FROM "/Users/yashwanth/Documents/GWU/Sem 3/Data Mining/Class 2/Class Material/ml-latest-small/ratings.csv";
CREATE TEMPORARY VIEW tags AS SELECT * FROM "/Users/yashwanth/Documents/GWU/Sem 3/Data Mining/Class 2/Class Material/ml-latest-small/tags.csv";



